[package]
edition = "2021"
name = "minesweeper"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.23.2"
ctrlc = {version = "3.0", features = ["termination"]}
rand = "0.8.5"
